version: '2'
services:
  web:
    #image: shome-web
    build: .
    environment:
      CRM_ENDPOINT: http://crm:10001/
    stdin_open: true
    tty: true
    links:
    - crm:crm
    ports:
    - 10000:3000/tcp
  crm:
    #image: shome-crm
    build: ../shome-cms
    stdin_open: true
    tty: true
    ports:
    - 10001:1337/tcp
  proxy:
    image: nginx:1.21.3
    environment:
      - TZ=${TZ}
    volumes:
      # - ./nginx/strapi.conf:/etc/nginx/sites-available/strapi.conf
      # - ./nginx/upstream.conf:/etc/nginx/conf.d/upstream.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web
      - crm
